name: cocktail_gen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  material_design_icons_flutter: ^7.0.7296
  riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.3.6
  auto_route: ^7.0.0
  chat_gpt_sdk: ^2.2.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  test: ^1.24.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
